@rootURL = http://localhost:8000
@apiEP = {{rootURL}}/api/v1
@userAPI = {{apiEP}}/users

### Post user 
POST {{userAPI}}
Content-Type: application/json

{
    "fName": "test",
    "lName": "shrestha",
    "phone": "4104444444",
    "email": "test@gmail.com",
    "password": "123456"
}

### Login user 
POST {{userAPI}}/login
Content-Type: application/json

{
    "email": "test@gmail.com",
    "password": "123456"
}

### user profile
GET {{userAPI}}
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3RAZ21haWwuY29tIiwiaWF0IjoxNzMyNjY1MzY0LCJleHAiOjE3MzI2NjYyNjR9.o1qCL8m4zU2Ezps1uGMytluS_r871CBz0vzy21EzfTc

### get new access jwt
GET {{userAPI}}/refresh-accessjwt
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3RAZ21haWwuY29tIiwiaWF0IjoxNzMyNjY1NjI3LCJleHAiOjE3MzUyNTc2Mjd9.webED2MEpMJAe_KuexcvqDzBkwxIaQsOGrIUVFBsVOE